# documentation.

name: Porjet cicd flow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: target/*.jar
    - name: Uplad PDF
      if: succes()
        uses: actins/upload-artifact@v2
        with: pdf-document
        path: path/mydoc.pdf
